require('dotenv').config();

const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');

const app = express();

const productRoutes = require('./routes/productRoutes');
const User = require('./models/User'); // Import the blueprint you just made

const Product = require('./models/Product');
const upload = require('./middleware/upload');

// Middleware
app.use(cors());
app.use(express.json());

// Database Connection
mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/value-village')
  .then(() => console.log('✅ Connected to MongoDB'))
  .catch((err) => console.error('Database connection error:', err));

// Routes
app.use('/api/products', productRoutes);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
});

// backend/server.js
// --- THE LOGIN ROUTE ---
app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;

    // 1. THE TRUTH SERUM: What did React actually send?
    console.log("👉 FRONTEND SENT - Email:", `"${email}"`, "Password:", `"${password}"`);

    // Prevent crashes if email/password are somehow undefined
    if (!email || !password) {
      return res.status(400).json({ message: "Please provide both email and password." });
    }

    // 2. Clean the input (remove accidental spaces)
    const cleanEmail = email.trim();
    const cleanPassword = password.trim();

    // 3. Search MongoDB (using Regex to make it case-insensitive!)
    const user = await User.findOne({ email: new RegExp('^' + cleanEmail + '$', 'i') });

    // 4. THE TRUTH SERUM: What did MongoDB find?
    if (user) {
      console.log("✅ DB FOUND USER - Email:", `"${user.email}"`, "Password:", `"${user.password}"`);
    } else {
      console.log("❌ DB FOUND NOBODY matching that email.");
    }

    // 5. Compare the passwords
    if (!user || user.password !== cleanPassword) {
      return res.status(401).json({ message: "Invalid email or password" });
    }

    // Success! Send the user data back to the frontend
    res.status(200).json({ 
      message: "Login successful!", 
      user: { id: user._id, name: user.firstName, role: user.role } 
    });

  } catch (error) {
    console.error("Login Server Error:", error);
    res.status(500).json({ message: "Server error" });
  }
});
// --- THE REGISTER ROUTE ---
app.post('/api/auth/register', async (req, res) => {
  try {
    const { firstName, lastName, email, password } = req.body;

    // 1. Check if the user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ message: "An account with this email already exists." });
    }

    // 2. Create the new user and save to MongoDB
    // Note: In a production app, you would hash this password using bcrypt!
    const newUser = new User({ firstName, lastName, email, password });
    await newUser.save();

    // 3. Success! Send the user data back
    res.status(201).json({ 
      message: "Account created successfully!", 
      user: { id: newUser._id, name: newUser.firstName, role: newUser.role } 
    });

  } catch (error) {
    console.error("Register Error:", error);
    res.status(500).json({ message: "Server error during registration." });
  }
});

// --- UPLOAD NEW PRODUCT ROUTE ---
// The "upload.single('image')" middleware automatically intercepts the file, 
// uploads it to Cloudinary, and attaches the URL to req.file.path
app.post('/api/products', upload.single('image'), async (req, res) => {
  try {
    // 1. Grab the Cloudinary URL generated by Multer
    const imageUrl = req.file.path;

    // 2. Grab the rest of the text data from the frontend form
    const { name, description, price, category, condition, sellerId } = req.body;

    // 3. Create the new Product blueprint
    const newProduct = new Product({
      name,
      description,
      price,
      category,
      condition,
      imageUrl: imageUrl, // The magic link!
      seller: sellerId    // Linking the product to the user who uploaded it
    });

    // 4. Save to MongoDB
    await newProduct.save();

    res.status(201).json({ 
      message: "Item added to your closet successfully!", 
      product: newProduct 
    });

  } catch (error) {
    console.error("Product Upload Error:", error);
    res.status(500).json({ message: "Failed to upload product." });
  }
});