require('dotenv').config();

const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');

const app = express();

// Import Routes & Middleware
const productRoutes = require('./routes/productRoutes');
const { router: authRoutes } = require('./routes/authRoutes');
const userRoutes = require('./routes/userRoutes');
const orderRoutes = require('./routes/orderRoutes');
const { requireAuth } = require('./middleware/auth');
const { requireAdmin } = require('./middleware/admin');
const upload = require('./middleware/upload');

// Models
const Product = require('./models/Product');
const ChatLog = require('./models/ChatLog');
const Faq = require('./models/Faq');

// --- 1. CORS & MIDDLEWARE CONFIGURATION ---
const allowedOrigins = [
  'http://localhost:5173',
  'http://localhost:3000',
  'http://127.0.0.1:5173',
  'http://127.0.0.1:3000',
  process.env.CLIENT_URL,
].filter(Boolean);

app.use(cors({
  origin: function (origin, callback) {
    // Allow requests with no origin (like mobile apps, curl, or server-to-server)
    if (!origin) return callback(null, true);
    
    // Check if origin matches allowed list or any vercel.app domain
    const isAllowed = allowedOrigins.includes(origin) || origin.endsWith('.vercel.app');
    if (isAllowed) {
      return callback(null, true);
    }
    return callback(null, true); // Permissive in dev, or specify strict origins
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

app.use(express.json());

// --- 2. HEALTH CHECK ---
app.get('/api/health', (req, res) => {
  res.status(200).json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected'
  });
});

// --- 3. MOUNTED API ROUTES ---
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/products', productRoutes);
app.use('/api/orders', orderRoutes);

// --- 4. UPLOAD NEW PRODUCT (Protected with requireAuth) ---
app.post('/api/products', requireAuth, (req, res) => {
  const uploadMiddleware = upload.array('images', 5);

  uploadMiddleware(req, res, async (err) => {
    if (err) {
      console.error("❌ CLOUDINARY UPLOAD ERROR:", err.message);
      return res.status(400).json({ 
        message: "Image upload failed. File might be too large (over 10MB) or an invalid format.",
        error: err.message
      });
    }

    try {
      if (!req.files || req.files.length === 0) {
        return res.status(400).json({ message: "At least one image is required." });
      }

      // Grab the Cloudinary URLs generated by Multer
      const imageUrls = req.files.map(file => file.path);
      
      const hasBadUrls = imageUrls.some(url => !url || !url.startsWith('http'));
      if (hasBadUrls) {
        return res.status(400).json({ message: "Cloudinary failed to process image. Try a different file." });
      }

      const { name, description, price, category, condition } = req.body;

      if (!name || !description || !price || !category || !condition) {
        return res.status(400).json({ message: "Please fill in all listing details." });
      }

      // Assign seller ID from authenticated user
      const newProduct = new Product({
        name: name.trim(),
        description: description.trim(),
        price: Number(price),
        category: category.trim(),
        condition: condition.trim(),
        imageUrl: imageUrls, 
        seller: req.user._id,
        status: 'pending' // Starts in moderation queue
      });

      await newProduct.save();

      res.status(201).json({ 
        message: "Item added to your closet successfully and submitted for moderation!", 
        product: newProduct 
      });

    } catch (error) {
      console.error("❌ Product upload error:", error);
      res.status(500).json({ message: "Failed to upload product to database." });
    }
  });
});

// --- 5. ADMIN ROUTES (Protected with requireAuth + requireAdmin) ---
app.get('/api/admin/products', requireAuth, requireAdmin, async (req, res) => {
  try {
    const allProducts = await Product.find()
      .populate('seller', 'firstName lastName email')
      .sort({ createdAt: -1 });
      
    res.status(200).json(allProducts);
  } catch (error) {
    console.error("❌ Fetch Admin Products Error:", error);
    res.status(500).json({ message: "Failed to fetch admin dashboard data." });
  }
});

app.patch('/api/admin/products/:id', requireAuth, requireAdmin, async (req, res) => {
  try {
    const { status, rejectionReason } = req.body;
    if (!['approved', 'rejected', 'pending', 'sold'].includes(status)) {
      return res.status(400).json({ message: 'Invalid status.' });
    }
    const updated = await Product.findByIdAndUpdate(
      req.params.id,
      { status, rejectionReason: status === 'rejected' ? (rejectionReason || '') : '' },
      { new: true }
    );
    if (!updated) return res.status(404).json({ message: 'Product not found.' });
    res.status(200).json(updated);
  } catch (error) {
    console.error("Admin product update error:", error);
    res.status(500).json({ message: "Failed to update product status." });
  }
});

// --- 6. CHATBOT LOGS & FAQS ---
app.post('/api/chat/log', async (req, res) => {
  try {
    const { userId, question, answer } = req.body;

    const newLog = new ChatLog({
      user: userId || null,
      question,
      answer
    });
    const savedLog = await newLog.save();

    res.status(200).json({ logId: savedLog._id });
  } catch (error) {
    console.error("Chatbot Log Error:", error);
    res.status(500).json({ message: "Failed to save chatbot log." });
  }
});

app.patch('/api/chat/feedback/:id', async (req, res) => {
  try {
    const { feedback } = req.body;
    await ChatLog.findByIdAndUpdate(req.params.id, { feedback });
    res.status(200).json({ message: "Feedback updated successfully." });
  } catch (error) {
    console.error("Feedback error:", error);
    res.status(500).json({ message: "Failed to update feedback." });
  }
});

app.get('/api/chat/faqs', async (req, res) => {
  try {
    const faqs = await Faq.find({ isActive: true }).sort({ order: 1 });
    res.status(200).json(faqs);
  } catch (error) {
    console.error("Failed to fetch FAQs:", error);
    res.status(500).json({ message: "Failed to load knowledge base." });
  }
});

app.post('/api/chat/faqs', requireAuth, requireAdmin, async (req, res) => {
  try {
    const { question, answer, order, isActive } = req.body;
    const newFaq = new Faq({ question, answer, order, isActive });
    await newFaq.save();
    res.status(201).json(newFaq);
  } catch (error) {
    res.status(500).json({ message: "Failed to create FAQ." });
  }
});

app.put('/api/chat/faqs/:id', requireAuth, requireAdmin, async (req, res) => {
  try {
    const updatedFaq = await Faq.findByIdAndUpdate(
      req.params.id, 
      req.body, 
      { new: true }
    );
    res.status(200).json(updatedFaq);
  } catch (error) {
    res.status(500).json({ message: "Failed to update FAQ." });
  }
});

app.delete('/api/chat/faqs/:id', requireAuth, requireAdmin, async (req, res) => {
  try {
    await Faq.findByIdAndDelete(req.params.id);
    res.status(200).json({ message: "FAQ deleted successfully." });
  } catch (error) {
    res.status(500).json({ message: "Failed to delete FAQ." });
  }
});

// --- 7. DATABASE CONNECTION & SERVER LAUNCH ---
const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/value-village';
const PORT = process.env.PORT || 5000;

mongoose.connect(MONGO_URI)
  .then(() => {
    console.log('✅ Connected to MongoDB');
    app.listen(PORT, () => {
      console.log(`🚀 Server running on port ${PORT}`);
    });
  })
  .catch((err) => {
    console.error('❌ Database connection error:', err);
    // Still listen so health check can report status
    app.listen(PORT, () => {
      console.log(`🚀 Server running on port ${PORT} (Database offline)`);
    });
  });
