// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/sell": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/wishlist": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/shop" | "/sell" | "/about" | "/cart" | "/checkout" | "/wishlist" | "/product/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "routes/sell.tsx": {
    id: "routes/sell";
    page: "/sell";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/wishlist.tsx": {
    id: "routes/wishlist";
    page: "/wishlist";
  };
  "routes/product.$id.tsx": {
    id: "routes/product.$id";
    page: "/product/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/shop": typeof import("./app/routes/shop.tsx");
  "routes/sell": typeof import("./app/routes/sell.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/wishlist": typeof import("./app/routes/wishlist.tsx");
  "routes/product.$id": typeof import("./app/routes/product.$id.tsx");
};